# -*- coding: utf-8 -*-
"""Translator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vF-BD3VFYG4X8g3SNpr5aveVMF8680hp
"""

!pip install googletrans==4.0.0rc1

from googletrans import Translator

def translate_english_to_hindi(word):
    translator = Translator(service_urls=['translate.google.com'])
    translation = translator.translate(word, src='en', dest='hi')
    translated_word = translation.text
    return translated_word
def translate_english_to_tamil(word):
    translator = Translator(service_urls=['translate.google.com'])
    translation = translator.translate(word, src='en', dest='tamil')
    translated_word = translation.text
    return translated_word
def translate_english_to_telugu(word):
  translator = Translator(service_urls=['translate.google.com'])
  translation = translator.translate(word, src='en', dest='telugu')
  translated_word = translation.text
  return translated_word
def translate_english_to_malayalam(word):
  translator = Translator(service_urls=['translate.google.com'])
  translation = translator.translate(word, src='en', dest='malayalam')
  translated_word = translation.text
  return translated_word
def translate_english_to_marathi(word):
  translator = Translator(service_urls=['translate.google.com'])
  translation = translator.translate(word, src='en', dest='marathi')
  translated_word = translation.text
  return translated_word

english_word = input('Enter an English word: ')

hindi_translation = translate_english_to_hindi(english_word)
print(f'Hindi translation of "{english_word}" is "{hindi_translation}"')

tamil_translation = translate_english_to_tamil(english_word)
print(f'Tamil translation of "{english_word}" is "{tamil_translation}"')

telugu_translation = translate_english_to_telugu(english_word)
print(f'Telugu translation of "{english_word}" is "{telugu_translation}"')

malayalam_translation = translate_english_to_malayalam(english_word)
print(f'Malayalam translation of "{english_word}" is "{malayalam_translation}"')

marathi_translation = translate_english_to_marathi(english_word)
print(f'Marathi translation of "{english_word}" is "{marathi_translation}"')